# tasks file for apache
- name: Install Apache (Ubuntu)
  become: yes
  apt:
    name: apache2
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Apache (CentOS)
  become: yes
  package:
    name: httpd
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Copy HTML file
  copy:
    src: /home/eze/ansible_study/roles/apache/files/index.html
    dest: /var/www/html/index.html
  
- name: start and enable httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"
