---
- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update package cache
      package:
        name: "*"
        state: latest
        update_cache: yes

    - name: Upgrade packages
      package:
        name: "*"
        state: latest

    - name: Update system packages (Red Hat/CentOS)
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update system packages (Debian/Ubuntu)
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"

    - name: Update system packages (SUSE)
      zypper:
        name: "*"
        state: latest
      when: ansible_os_family == "Suse"

    - name: Update system packages (Arch Linux)
      package:
        name: "*"
        state: latest
      when: ansible_os_family == "Archlinux"


    - name: Install PHP on Ubuntu
      apt:
        name: php
        state: present
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install PHP on CentOS
      yum:
        name: php
        state: present
      when: ansible_facts['distribution'] == 'CentOS'

  roles:
#    - script-runner
     - apache
#    - nginx
#    - terraform
#    - docker
