# tasks file for script-runner
- name: Copy script file to the remote host
  copy:
    src: script.sh
    dest: /home/phoenix/ansible_study/roles/script-runner/files/script.sh
    mode: "0755"

- name: Execute the script
  shell: /home/phoenix/ansible_study/roles/script-runner/files/script.sh
  args:
    executable: /bin/bash
