# tasks file for nginx
- name: Install Nginx
  become: yes
  package:
    name: nginx
    state: present

- name: Start Nginx service
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes

#- name: Fetch nginx.conf from remote host
#  become: yes
#  fetch:
#    src: /etc/nginx/sites-available/default
#    dest: /etc/nginx/nginx.conf
#    flat: yes
#    validate_checksum: yes

- name: Create nginx default configuration file
  become: yes
  copy:
    content: |
      # Your nginx configuration content goes here
      # Example:
      server {
          listen 80;
          server_name example.com;
          root /var/www/html;
          index index.html;
      }
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: "0644"
  notify: Restart Nginx

- name: Copy and modify nginx default configuration file
  become: yes
  template:
    src: /root/ansible/ansible_study/templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: "0644"
  notify: Restart Nginx


#- name: Copy updated nginx.conf
#  become: yes
#  copy:
#    src: /etc/nginx/sites-available/default
#    dest: /etc/nginx/nginx.conf
#    owner: root
#    group: root
#    mode: "0644"
#    remote_src: yes
#  notify: Restart Nginx


- name: Restart Nginx
  become: yes
  service:
    name: nginx
    state: restarted

